### PR TITLE
chore: Run SCA in git mode

### PR DESCRIPTION
**Pull request by edoardopirovano**
This should get us source control references.

### CODE REVIEW

**Review by linpengzhang — CHANGES_REQUESTED** [review]
could you add https://github.com/lacework-dev/sca/blob/main/cmd/dir.go#L149-L166 in https://github.com/lacework-dev/sca/blob/main/cmd/git.go?

**Comment by edoardopirovano** [comment]
Aha, good point. Done in https://github.com/lacework-dev/sca/pull/51.

**Review by linpengzhang — APPROVED** [review]
lgtm, let's wait for the ci to finish and then we can bump a new version of sca.

**Comment by edoardopirovano** [comment]
Hmm, weird. 0.0.23 isn't actually out yet (I saw the tag and thought it was but the CI is still running), but the CLI happily installed 0.0.22 instead without an error! And that's also made it into the cache as 0.0.23 🙁

**Comment by linpengzhang** [comment]
> 

great spot!

**Pull request merged**
